### ISSUE TITLE
Multiple instances of all calling functions/instances while profiling using intel compiler

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tyoma/micro-profiler#21]
```
What steps will reproduce the problem?
1.Added micro-profiler in MSVS 2010 professional edition. Till this it is 
profiling as expected. 
2.Than toggle compiler to Intel Parallel Studio C++ professional compiler.
3.Code execution for profiling.

What is the expected output? What do you see instead?
Ans.The profiler should profile of each functions and shows its individuals 
timings. But it shows multiple instances of functions and some of them are with 
0 Second execution time which is practically incorrect, as mentioned in 
attached file of both the compiler.

What version of the product are you using? On what operating system?
Ans.I have embedded "Intel Compiler XE 2015 professional edition for C++" on 
Windows 7 64-bit OS and Intel core i5 2400 quadcore CPU.

Please provide any additional information below.
I covered almost.


```

Original issue reported on code.google.com by `bhattite...@gmail.com` on 17 Oct 2014 at 1:21

Attachments:
* [Through_IntelCompiler.png](https://storage.googleapis.com/google-code-attachments/micro-profiler/issue-21/comment-0/Through_IntelCompiler.png)
* [Through_MSVC.PNG](https://storage.googleapis.com/google-code-attachments/micro-profiler/issue-21/comment-0/Through_MSVC.PNG)

**Comment by tyoma** [comment]
MicroProfiler differentiates functions by their addresses, not the names. Apparently, Intel compiler decided to split DetectionAlgorithm9 function into several instances (a wild guess: the function had a switch inside with branching deducible from an input argument).

Zero call time is a normal situation, when a function was entered, did nested calls, but not exited yet (for instance, it has a message loop inside).
