### ISSUE TITLE
Not seeing GUI front end or enable profiling menu item.

### ISSUE THREAD

**Issue by spcmicro** [tyoma/micro-profiler#26]
I have tried to install micro profiler on 2 systems. One is a Windows 7 64 bit system running VS 2008, 2010 and 2015.
The second system is a Windows 10 64 bit system also running VS 2008, 2010 and 2015.
The installer provides feedback saying it is modifying all of the versions of VS for each system so it appears as if the installation was OK.
I do not see a GUI front end application anywhere on the system and in all versions of Visual Studio, is this an app that gets installed? Also the "Enable Profiling" option doesn't not appear in the context sensitive menu in Solution Explorer in any version of VS that I try. 
One system is my home system on which I am the administrator.
I must be doing something wrong...

**Comment by tyoma** [comment]
I pushed new version to marketplace - it should fix your problem.
