### ISSUE TITLE
Static Library Profiling - Visual Studio 2013

### ISSUE THREAD

**Issue by belmich1** [tyoma/micro-profiler#29]
We used your tool with great success in the past while profiling one of our DLLs. In a newer release, we had a need to refactor the DLL into a static library and a DLL. Now, all the code is in the static library and we simply link the DLL against the static library. Some part of our software links statically to the .lib and other parts link against the .dll.

We used to enable profiling on the DLL and that worked just fine. Now, when I Enable Profiling on the DLL only, I get the Micro-Profiler dialog that pops up at runtime but no statistics. Therefore, I assumed that I needed to enable profiling on the static library. When I try that, I consistently get: error LNK1104: cannot open file 'micro-profiler.lib'.

I have read in the User Reviews on your website that another of your client is experiencing similar issues. I am not sure I quite follow what you mean by this answer:

Quote from Artem Gevorkyan:
Unfortunately, profiling static libs is still tricky: you have to turn profiling on then off (but w/o removing profiling; this will simply add initializer cpp to the project) suport on exe, then add both /GH /Gh command line options to compiler in lib's project configuration.
Sorry for the inconvenience - I'll add this soon.

When I select `Enable Profiling` on my project, I get an extra menu item that is labeled `Remove Profiling Support`. If I uncheck the `Enable Profiling` menu item but do not click the `Remove Profiling Support,` the /GH /gh are removed in the Command-Line options for my project. I have no idea how to get this working at this time.

**Comment by belmich1** [comment]
Never mind. I have rebuilt my solution change a few build options that are unrelated to Micro-Profiler and now it works. Thanks.

**Comment by tyoma** [comment]
thanks for the interest in the profiler and solving the problem!
