### ISSUE TITLE
Unit of Measure used by Raw Statistics

### ISSUE THREAD

**Issue by belmich1** [tyoma/micro-profiler#30]
In the screenshot, on Visual Studio Gallery, https://visualstudiogallery.msdn.microsoft.com/133d5764-b32b-4ec9-8ee8-5546eca64584/showImage/127075, we see that some of the time-based statistics are displayed in various unit of measure (i.e. seconds, miliseconds, microseconds, nanoseconds, etc...). 

When we extract the statistics, we do not have any unit of measurement associated with the raw data. Therefore, I assume, that in that case, all the raw numbers are in one single unit of measure.

If I am right, which unit of measure would that be?

Thanks.

**Comment by tyoma** [comment]
all times are in seconds, when pulling a snapshot )
