### ISSUE TITLE
Not able to link my projects

### ISSUE THREAD

**Issue by jlohiya** [tyoma/micro-profiler#31]
I am seeing below errors while linking. It used to work few days work but currently not working. I am not able to identify the root cause. Please help in running microprofiler again.

Error	54	error LNK2001: unresolved external symbol __penter
Error	51	error LNK2001: unresolved external symbol __pexit	
Error	59	error LNK2019: unresolved external symbol __pexit referenced in function "public: __thiscall

**Comment by tyoma** [comment]
If you're integrating mp manually, you have to add cpp file in mp's installation folder. It will make sure  the library required is included as well as it will afd the initialization necessary.

**Comment by sirius-black9999** [comment]
i actually got this after trying to integrate this into a project automatically, in VS 2017, it seems to have added references to my project but there's no option to remove profiling and it also seems to be unable to find the relevant .dll files...

**Comment by tyoma** [comment]
Did you uninstall previous versions if any?
Did you try the infamous "uninstall (from Extensions and Updates) / reboot Windows (relogin should be enough, I guess) / install again (from Extensions and Updates)" sequence for MicroProfiler in VisualStudio 2017?
Will it ask to restart Visual Studio after that (it should)?
If you try 'Enable Profiling' and then open micro-profiler.initializer.cpp's folder (Open Container Folder in file's editor tab) - what are the files there? Does that folder container micro-profiler.x64.dll?
Thanks,
Artem

**Comment by onemanmmo** [comment]
I had a similar problem in Visual Studio 2010 after using the profiler, it turns out it had left the /GH /Gh compiler switches in my project settings after I had disabled the profiler using its menu option so I couldn't do a regular build.

**Comment by tyoma** [comment]
This may happen when you enable profile in several configurations, then remove support from one. That's a defect for sure, but I don't this what @sirius-black9999 faced...

**Comment by sirius-black9999** [comment]
sorry for not responding sooner, i did a full reinstall already, hadn't rebooted since. i have now and the problem with VS 2017 is still present after a reboot

i did find .lib files in the project, but not a .dll: https://puu.sh/z2tIb/f39dee6450.png

since i installed via the .visx installer and closed VS while installing i did not get a prompt to reboot,

**Comment by tyoma** [comment]
libs are copied to the project location (there's some room to simplify this - to include libs from their original location), but I meant the package installation location.
Can you please trace the directory where micro-profiler.initializer.cpp (the file added to the project when you enable profiling) is located? dlls must present in the same dir (it usually is some weirdly named directory in /users/<username>/AppData/Local/Microsoft/Visual Studio/15.0/Extension).

**Comment by tyoma** [comment]
Can you please find me on LinkedIn (https://www.linkedin.com/in/artem-gevorkyan-5a026a3/) so we can share IMs? It would be easier just to talk this issues over...

**Comment by tyoma** [comment]
out of curiosity - do you disable iterator debugging by defining _HAS_ITERATOR_DEBUGGING in precompiled header?

**Comment by sirius-black9999** [comment]
i just did, i'm not using a precompiled header, and none of my header files define that symbol (unless SDL/GLEW/GLM defines it somewhere)

**Comment by tyoma** [comment]
Hey! I've fixed problem with '/GH /Gh' left behind. I also modified the way the library is attached to the project - it should be safer now and, I expect, there will be no unmarked 'Enable Profiling' items.
Can you try it out? This is the release (before I posted on marketplace):
https://github.com/tyoma/micro-profiler/releases/download/v1.2.596/micro-profiler.v1.2.596.0.vsix
Thanks!

**Comment by tyoma** [comment]
!!! Hold on, please, until I remove this message...

**Comment by tyoma** [comment]
I can confirm it's now working. Please try. If it works fine I'm publishing it on the Marketplace!
Thank you!

**Comment by tyoma** [comment]
I was able to reproduce the issues with 2017 integration - the new version fixes them all. It has been pushed to marketplace recently. Your Visual Studio should pick it up automatically, you may only need to restart it (open Extension s and Updates - there should be message that you need restart).
