### ISSUE TITLE
Integration with VS2017

### ISSUE THREAD

**Issue by jpouderoux** [tyoma/micro-profiler#32]
MicroProfiler is not yet compatible with VS2017 due to the changes that occurent in VS in way packages are loaded.

How can we make progress on this? 
We **really** need to have MicroProfiler in VS2017 :)

Best,
J.P

**Comment by tyoma** [comment]
I'd like to hear some advice on how to do that - on one hand I need to make mp dll visible for a program being profiled (i now reach this by adding to 'path' envvar the installation directory) in the other hand I'm adding a vcpackage, which in 2017 must be packed into vsix. I can add a package to visual studio folder, but how do I figure out, which installation should I use (bc vs2017 can have several instances)
Any help on this is greatly appreciated!!
Thank you!

**Comment by tyoma** [comment]
Hey! If it's not too late - the new version is available for VS 2017:
https://marketplace.visualstudio.com/items?itemName=ArtemGevorkyan.micro-profiler-vsix
You can now see it in the Extensions and Updates in Visual Studio.

**Comment by jpouderoux** [comment]
Awesome! Thanks a lot. Hope update for next VS version will be less effort.
