### ISSUE TITLE
Report window visibility

### ISSUE THREAD

**Issue by jpouderoux** [tyoma/micro-profiler#34]
Hi,
When running a program with Micro-Profiler enabled, the report window appears.
If you reduce it, it is not easy to make it appear again because it has no entry in the task
bar and no icon in VS interface. To make it appear again you have to reduce VS and show it again.
Then if you forget to close it but you thing you did because window is hidden and program terminated, making a change to the code and building it again produces a link error because the hidden window
of Micro-Profiler is still attached to the old code binary. Boring.
So I think it could be useful if Micro-Profiler could have an entry in the task bar.
What do you think?

Thanks,
Joachim

**Comment by tyoma** [comment]
Good issue! Actually two - report window not being part of IDE's native tool window chain and profiler locking profilee's pdb. The first is quite complex, while the other is something I can fix quite easy.

**Comment by tyoma** [comment]
Hi Joachim!

I've added support of listing opened profiler windows and the ability to close all to the new MicroProfiler menu in MSVS main menu. I haven't pushed it to Marketplace yet, but you can try it here:
https://github.com/tyoma/micro-profiler/releases/download/v1.2.598.0/micro-profiler.v1.2.598.0.vsix
Please, respond if it's what you needed.

thank you,
Artem
