### ISSUE TITLE
No Profiler Frontend/no statisticsfile while/after a profiling

### ISSUE THREAD

**Issue by ActionLuzifer** [tyoma/micro-profiler#37]
I just installed latest version (1.4.601.0) and use VS 2010 in Windows 7 x64.
After the installation I restarted the PC.

After that i set to a project in my solution the "enable profiling". It's a 32-Bit program, like the micro-profiler version.
Then i made a complete "rebuild solution" and started my program.

And nothing happens. I never saw a Frontend, and i can't find any file which could be written from MicroProfiler while the program was running.
I even can't find any entries in the menu of VS, where i could open the Frontend manually.

**Comment by tyoma** [comment]
So you installed *.x86.*.msi, correct?
Did you have any MP version installed before?
Do you see dllhost.exe process appearing in the task manager's processes list, when you run your program?
There's no "MicroProfiler" top-level menu in VS 2010, is this correct?

**Comment by tyoma** [comment]
One more question:
Does your program or any dll in it make explicit use of Windows Activation Contexts (like calling activation context API or referencing any particular regless of COM object)?

**Comment by ActionLuzifer** [comment]
> So you installed _.x86._.msi, correct?
--> True

> Did you have any MP version installed before?
--> No, i heard of MP today for the first time

> Do you see dllhost.exe process appearing in the task manager's processes list, when you run your program?
--> I'll check this later. Would this be good?

> There's no "MicroProfiler" top-level menu in VS 2010, is this correct?
--> No, that's not correct. I see the MicroProfiler in the menu, where i can select "open statistic...". That's why i thought maybe MP is writing always a log somewhere. But i didn't find one.
In View->Windows you can select many different windows. I was hoping to see MP somewhere, were i could start the Frontend manually.

> Does your program or any dll in it make explicit use of Windows Activation Contexts (like calling activation context API or referencing any particular regless of COM object)?
--> Huh, good question. Never heard of this API. But my project-dll is loaded in a bigger software. I'll check that.

**Comment by tyoma** [comment]
Most probably, if 1) you're seeing MicroProfiler's menu, 2) you were able to Enable profiling, 3) your app started normally -> the installation went fine.
If you're the part of a bigger system - then a problem Activation Context would be my bet. I'm digging into that right now.

**Comment by tyoma** [comment]
...and many thanks for response!

**Comment by ActionLuzifer** [comment]
I thank you, for your quick response! :)

**Comment by tyoma** [comment]
Can you please replace the file micro-profiler_x86.dll found in the installation directory with the one i've attached here and restart you application?
[micro-profiler_x86.zip](https://github.com/tyoma/micro-profiler/files/2497359/micro-profiler_x86.zip)
