### ISSUE TITLE
Internal function calls are missing

### ISSUE THREAD

**Issue by rold2007** [tyoma/micro-profiler#38]
I just tried micro-profiler on my project it looks like many internal calls are missing from the report. As you can see from the screenshot I have a function running for ~19**s** but when I look at the functions it calls there is only one function taking ~65**ms**. My function is actually calling many other functions so I'm wondering why these other function calls don't appear.

Could it be a bug in micro-profiler ? Is there anything I can do to identify why the other calls are missing ?

![missing calls](https://user-images.githubusercontent.com/507551/48679635-1dc86080-ebd6-11e8-9d75-61e3be61e8f6.png)

**Comment by rold2007** [comment]
FYI I'm using the latest version: v1.4.603

**Comment by tyoma** [comment]
Thanks!

**Comment by rold2007** [comment]
I tested by activating the _gh_ options for all projects and I can indeed see my function calls under the benchmarked function. I'll close this issue now. Looking forward for the completion of the non-intrusive branch !

**Comment by tyoma** [comment]
Thank you!
