### ISSUE TITLE
Standalone?

### ISSUE THREAD

**Issue by optomux** [tyoma/micro-profiler#39]
What happened to the standalone version? I'd like to use it from Qt Creator.

**Comment by tyoma** [comment]
Don’t worry, it’s all yours: https://marketplace.visualstudio.com/items?itemName=ArtemGevorkyan.micro-profiler-vsix
and if you need 32-bit only: https://marketplace.visualstudio.com/items?itemName=ArtemGevorkyan.MicroProfilerx86
