### ISSUE TITLE
Let's create an option to stop or pause profiling.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tyoma/micro-profiler#4]
```
It is very useful sometimes to have an option to start/stop profiling by 
demand. It allows us to look at results, investigate it etc., especially if we 
did profiling run for specific time of app work.

The best solution would be to implement kind of 'project' / 'workspace' 
objects, but it would require too much development for now I guess.

It also makes sense to allow to start profiler being turned OFF initially 
somehow (as optional flag).
```

Original issue reported on code.google.com by `4ekme...@gmail.com` on 18 Oct 2011 at 2:56

**Comment by pk1954** [comment]
I support this feature request. Sometimes it ist necessary to do some preparations before the application comes into a state where the time critical action happens. If there was away to turn profiling on only for the time critical phase, the profiling output would be "cleaner" and more significant.
I don't quite understand, what the  'project' / 'workspace' objects in the original request means. I could imagine either an API call to microprofiler, or an option in the debugger interface.

**Comment by SergeLalonde** [comment]
If you're going to have Start and Stop, you should have a Clear operation so that the profiling data collected so far can be cleared to start over.
These features would make this a killer extension (and it's already really good).

**Comment by tyoma** [comment]
@SergeLalonde the 'Clear' command is already there - it's the cross in the tiny toolbar on top of the statistics lists ('Clear' button in the standalone version).

**Comment by tyoma** [comment]
@pk1954 The author of that suggestion originally meant both - API and the toggle button. I'm going to implement the toggle button sooner. The API puts some implications on how to make it available with the minimal hassle, especially considering that I plan to eliminate the necessity of micro-profiler.initializer.cpp inclusion (yes, the only thing to include to the project will be the .lib for the collector's dll/so).

**Comment by tyoma** [comment]
@SergeLalonde, @pk1954 Guys, please check out this version - is that what you wanted?
https://github.com/tyoma/micro-profiler/releases/download/v1.5.613.0/micro-profiler.v1.5.613.0.vsix

The change is here: b88ebb7bf0d2715886c6b72343f5f2baef629fbb

**Comment by pk1954** [comment]
Yes, that's fine as for me.
