### ISSUE TITLE
How to see saved mpstats file

### ISSUE THREAD

**Issue by mukuact** [tyoma/micro-profiler#41]
Hi! 
Thank you for very useful extention!!!! It's very cool.

Then, I have an easy question now.
When click "save as " button and save it, how to use that file?

**Comment by tyoma** [comment]
Hi!

You can open the file saved from MicroProfiler menu integrated into VisualStudio main menu - there's a 'Open Statistics...' menu item.

thanks!

**Comment by mukuact** [comment]
Oh!, Sorry, I overlooked menu added.
Very Thanks!
