### ISSUE TITLE
Profiler GUI opens in unexpected Visual Studio instance

### ISSUE THREAD

**Issue by icnocop** [tyoma/micro-profiler#44]
Hi.

I noticed that the Profiler GUI opens in an unexpected Visual Studio instance.

Here are some steps to reproduce for example:
1. Close all instances of Visual Studio
2. Open SolutionA.sln in a new instance of Visual Studio
    In my scenario, this solution doesn't have any projects where profiling is enabled.
3. Open SolutionB.sln in a new instance of Visual Studio
    In my scenario, this solution doesn't have any projects where profiling is enabled.
4. Enable profiling for a project in SolutionB
5. Run the project with profiling enabled in Solution B.
    I clicked Debug > Start Debugging.
6. Notice the Profiler GUI opens in the first instance of Visual Studio, where SolutionA is loaded.
    I expected the Profiler GUI to open in second instance of Visual Studio where SolutionB is open, where my project with profiling enabled is.

Visual Studio 2015
MicroProfiler 1.4.605.0 (Visual Studio Extension)

Thank you.

**Comment by tyoma** [comment]
Implemented via IPC abstraction over sockets. As a bonus, this allows for remote profiling without DCOM involvement.
