### ISSUE TITLE
Need to convert from synchronously autoloaded extension to ascynchronous for VS2019

### ISSUE THREAD

**Issue by rold2007** [tyoma/micro-profiler#46]
When loading this extension in VS2019 there's a warning that it is using a deprecated feature. i.e. loading synchronously instead of asynchronously.

See [Microsoft's documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2019) about this issue.

**Comment by tyoma** [comment]
This is not possible yet, as there's no way to make async-autload native package. See this issue:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/1599
Once it is implemented in VisualStudio, I'll add a branch for VS2019+ to load MicroProfiler asynchronously.

**Comment by tyoma** [comment]
Hi David!

I've added the changes necessary for Visual Studio to load the extension asynchronously. Please, try the latest version - it shouldn't pop the 'deprecated api usage' message.
If you're satisfied with the change - please, close the issue.

thanks,
Artem

**Comment by rold2007** [comment]
All good, no more warning message with version 1.4.606.0 (released on 2019-07-14).
