### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pk1954** [tyoma/micro-profiler#51]
Hi Artem,
after being occupied by other things for some time, I recently came back to my C++ project and installed the latest version of microprofiler. Installation was ok, but build said: 
> 1>micro-profiler.initializer.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'c:\users\peter\appdata\local\microsoft\visualstudio\16.0_8dc9fbb5\extensions\3rjdygay.n1p\micro-profiler.initializer.cpp': No such file or directory

I found the microprofiler files in a different directory: 
C:\Users\peter\AppData\Local\Microsoft\VisualStudio\16.0_8dc9fbb5\Extensions\zg334nqg.10l

I renamed "zg334nqg.10l" to "3rjdygay.n1p" and the build worked. 

Microsoft Visual Studio Community 2019  Version 16.4.2
Microsoft Windows 10 Pro Version 10.0.18363 Build 18363
MicroProfiler Version 1.5.611.0

**Comment by tyoma** [comment]
Confirm - there's a mixup with how the location of the installation is identified.

**Comment by tyoma** [comment]
Fixed in commit c909687128653358748fed8886a469e425a90444

**Comment by pk1954** [comment]
I just installed version 1.6.616 without problems. Runs flawlessly.
