### ISSUE TITLE
Function names not displayed

### ISSUE THREAD

**Issue by pk1954** [tyoma/micro-profiler#52]
Hi,
after overcoming the build problem (see issue #51)  I enabled profiling and ran the application. The statistics page appears, all time values are visible, but the Function column is empty.
Any ideas, what I can do?
Regards
Peter

**Comment by tyoma** [comment]
Hi, Peter!
The names may now appear appear asynchronously within some time interval. Did you wait for them to appear? I can play with the priority of that thread - that may be the reason.
Thanks,
Artem

**Comment by pk1954** [comment]
Hi Artem,
I waited several minutes. To be sure I also tested it with a different application, which has a very low CPU load. Same behavior.

![screenshot](https://user-images.githubusercontent.com/25415300/72526001-b6ec1900-3865-11ea-8521-56c251ced7f6.jpg)

**Comment by tyoma** [comment]
interesting... I'm now thinking on adding logging - a long overdue task - to catch this situations. Can you wait for it? Meanwhile - you still can use older version: https://github.com/tyoma/micro-profiler/releases/download/v1.4.607.0/micro-profiler.v1.4.607.0.vsix

**Comment by JulianDiaz-KST** [comment]
Hi, I have experienced the same issue. I suspect that the culprit is the most recent [service update to VS 2017](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.9.19), as Microprofiler was working fine before this update and I don't believe anything else has changed in my environment. Unfortuantely I need to use 15.9 but there seems to be no way to roll back to a previous patch. :/

**Comment by tyoma** [comment]
then, maybe you have to check pdb mode in linker - if it set to ‘fast’ the symbols cannot be read by dbghelper, which mp is using

**Comment by pk1954** [comment]
Yes, the problem is caused by pdb mode in linker. I didn't set it to 'fast' explicitly, but by any strange reason it behaved like that. I'm not in the mood to investigate deeper into the issue. The main thing is: It works. From my point of view the issue can be closed. I hope JulianDiaz-KST also managed to solve the problem.

**Comment by e2-dunstan** [comment]
I too am having this problem. How do I change the pdb mode?

**Comment by pk1954** [comment]
Properties - Linker - Debugging - Generate Debug Info:
(/DEBUG) is ok
(/DEBUG:FASTLINK) causes the problem
didn't test the other option (/DEBUG:FULL)
