### ISSUE TITLE
Option to make columns wider

### ISSUE THREAD

**Issue by pk1954** [tyoma/micro-profiler#56]
In every MicroProfiler session my first activity is to make the columns wider. Initially they look like this: 
![image](https://user-images.githubusercontent.com/25415300/75550239-cbf5c380-5a31-11ea-8730-8ca4cb8c09b8.png)
I want them to look like this, so that I can read the numbers and the units:
![image](https://user-images.githubusercontent.com/25415300/75550358-0a8b7e00-5a32-11ea-963c-e0a5a49da130.png)
Ok, it doesn't take more than a few seconds to doubleclick the header separators, but it would make an already very good user interface a little bit more practical. I understand, that my preference cannot be the default behaviour. Maybe a simple button "expand columns" or something like the Excel way, mark several columns and expand them with a singe doubleclick.
... Would be a nice improvement

**Comment by tyoma** [comment]
This is actually a defect - I had columns width saving logic in a standalone version, but apparently it got broken when sharing the code with integrated frontend.

**Comment by pk1954** [comment]
Saving user preferences is of course the optimal solution. I'm looking forward to you getting it working again.
By the way, where do you store user preferences? In the registry, in user\AppData?  I've been looking for different methods and have not yet found something that completely convinces me.

**Comment by tyoma** [comment]
The settings are historically been persisted it in the registry under: HKEY_CURRENT_USER\Software\gevorkyan.org\MicroProfiler
But in the VSPackage the storing logic got broken, so the columns take their widths (and names :) ) from registry, but never update it.
You can play with those settings and see the result in VisualStudio.
For VSPackage I plan to update settings to be stored in persistence bags that Visual Studio offers to its plugins.

**Comment by tyoma** [comment]
Hi Peter!

Please, check out for this release: https://github.com/tyoma/micro-profiler/releases/download/v1.6.619.0/micro-profiler.v1.6.619.0.vsix  - it has the issue fixed. If so, please close it.

thanks!

**Comment by pk1954** [comment]
It works. Thank you.
