### ISSUE TITLE
"Visual Studio has encountered an unexpected error" when enabling profiling in VS2019 .NET projects

### ISSUE THREAD

**Issue by SergeLalonde** [tyoma/micro-profiler#61]
The title says it all. It doesn't even check out the project from TFS before issuing the error:

![image](https://user-images.githubusercontent.com/44875727/88324556-d91d9280-ccf1-11ea-828d-a673fe8855f0.png)

I tried with 1.6.622.0 and a co-worker tried with 1.7.624.0. Same problem.
I tried checking out the project file before enabling the profiling. Same problem.

However, it properly enables a C++ project in VS2019.

Is there a workaround?

**Comment by tyoma** [comment]
Hi Serge, the profiler is for native C++ applications only. The tagline on MarketPlace says this explicitely. It can also be enabled for native part of the code of C++ projects (manually).

A better warning is probably required...
