### ISSUE TITLE
Function names missing in profiler log view

### ISSUE THREAD

**Issue by klukander** [tyoma/micro-profiler#62]
Hi,

I'm running micro-profiler on VS2019 Community and was able to enable profiling and run the code (I need to run VS as admin for this because of the installation path to the microprofiler an dthe MICROPROFILEDIR point to a restricted directory location).

I've successfully used this before on VS2017 , but now on VS2019 it seems to work ok other than that in the profiler view afterwards I get the table for running times and all, but the function names column is completely empty?

**Comment by tyoma** [comment]
Please, see other issues. Most probably you have /DEBUG:FASTLINK option set in linker settings. Use simply /DEBUG or /DEBUG:FULL.

**Comment by klukander** [comment]
Thanks, I don't know how I didn't the issue from before. I had /DEBUG, changed it to /DEBUG:FULL, and now it works. Thanks for a really great tool!

**Comment by tyoma** [comment]
@klukander if you don't mind, please, find a time to star me here and write a review on https://marketplace.visualstudio.com/items?itemName=ArtemGevorkyan.MicroProfilerx64x86
Thanks again for your effort and appreciation!
