### ISSUE TITLE
Wrong function names

### ISSUE THREAD

**Issue by Appeldorian** [tyoma/micro-profiler#70]
I'm profiling a medium sized, heavily templated and multithreaded project and atleast some function names are just completely wrong. The profiler output says that a certain function has been called millions of times to my surprise. I put a std::cout statement inside the function to verify this, but cout statement only appeared when the function was expected to be called and not millions of times...

I understand this would be hard to reproduce on your end without this specific project, but is this something that can be because of a bad configuration or something? What could cause this issue?

In the following image you can see the call. I censored the function names as it is a closed source project for a publicly known company with the company's name in the function name, but it shouldn't matter anyways.

![microprofiler](https://user-images.githubusercontent.com/69849518/115543047-3e161100-a2a1-11eb-96c1-f73b47162beb.PNG)

I'm using the most recent version of the MicroProfiler plugin for Visual Studio in VS2015 on a Windows 10 computer. Let me know if you need more information.

Thanks!

**Comment by tyoma** [comment]
Hi @Appeldorian!

May it be the functions got aliased? This usually occurs when 'Enable COMDAT Folding' is enabled in linker's optimizations. The linker in this case throws away duplicated function definitions (very probable, when using templates for different types, but the final instantiations are similar codewise).
It also would be helpful if you clarify what portion of the names are displayed correctly.
My course of actions would be:
1) check 'comdat folding' and 'optimize references' in linker's optimizations;
2) clean (and check if there're any .pdb left in the directories of interest) and then rebuild;
3) while under debugging AND profiling, double click (in a main stats view) on a function you're sure has a wrong name displayed, the profiler will navigate VS editor to that function. Set a breakpoint there and see if flow actually gets there.

Thank you!
Artem

**Comment by Appeldorian** [comment]
Hello Artem,

Turning off COMDAT folding indeed solved the problem 👍 

Thanks a lot for your quick reply and your fantastic application!

All the best,
Dorian

**Comment by tyoma** [comment]
Thank you Dorian (@Appeldorian)!

If you can, please leave a review on Visual Studio Marketplace.

Thanks again for the interest in my product,
Artem

**Comment by BrunoC-L** [comment]
Hi, in my case there are no function qualified names displayed, my project has 2 libraries and 1 executable, I enabled profiling on all of them and turned off COMDAT folding for the executable.

surely I am missing a basic step but I couldn't see anything in the README that would explain this.

I saw the video, you select run without debugging, I tried while debugging and without debugging and got the same result.

windows10 vs2019, I am using the extension from visual studio, not the source.

Thank you for your time and open source project! looking forward to use it.

**Comment by tyoma** [comment]
Hi @BrunoC-L!

You're probably facing the issue that has risen a few times before - https://github.com/tyoma/micro-profiler/issues/62
I probably need to add some detection of 'fastlink' and add some kind of warning (but _where_?) on an attempt to run such a process with profiling on...

Thank you,
Artem
