### ISSUE TITLE
Feature Request: Function overview with counts and data from all threads.

### ISSUE THREAD

**Issue by StefanS52u1** [tyoma/micro-profiler#71]
Hi, we have a 32-bit large windows application, using up to a few hundreds of threads. from a memory pool. The threads will used "on demand" for tasks. Every task will be assigned "randomly" to the threads from a thread pool. The thread pool will construct and destruct these threads (after not being used for a certain time period). Therefore the views and table within the profiler are more or less not usable, because each function entry and exit will be called by many threads. 

For these kind of applications, i would prefer a view within devstudio, neglecting all thread id for the function calls, like it was in the version 1.6 and earlier. Could it be possible to add this feature ?

I switched back to version 1.6.615 - the memory footprint of the collector is also much lower. But i guess this version will not be supported any more. It would be nice to switch optionally to a view a'la 1.6.615 without thread information.

**Comment by tyoma** [comment]
Good issue Stefan (@StefanS52u1)!
I'll take it for development.

**Comment by StefanS52u1** [comment]
Hi, is there any progress concerning this feature?.  Without this feature the usage of the actual microprofiler if still not possible with the described circumstances. If this would reduce the efforts, i would suggest a quick and dirty solution (configurable) to ignore the thread id at all during collecting the data.

**Comment by tyoma** [comment]
hi @StefanS52u1! working on it. i'm reconsidering the way the data is structured - this may even open a door to collect true call stacks, rather than just parents/callees stats, but it may require summing up values, while building a view.
i can also make a special interim branch with the change you've mentioned if that works for you

**Comment by StefanS52u1** [comment]
Hi Artem, a interim branch would be nice, i tried to make the changes on my own - but at the moment i'm facing a build issue: The extension.vsixmanifest seems not be build of the "vsix" file. (I cloned the 2.0.637 version.)

**Comment by tyoma** [comment]
shoot, i'm very sorry, @StefanS52u1 - there was a type apparently in the name of the variable. now it's fixed - 7923089a53602874e6770d9c174f8605ece1ce77

**Comment by StefanS52u1** [comment]
Hi @tyoma , it would be o.k. for me to choose either "all threads" ignoring the thread info at all - or the actual info per thread. That might be easier to implement. The switch could be done within the ui part of the micro-profiler.

**Comment by tyoma** [comment]
@StefanS52u1  as an update: i'm implementing a grouping view, so that stats from multiple rows (for different threads, for instance) can be summed up.

**Comment by StefanS52u1** [comment]
Hi Tyoma, do you have any pre-release versions for testing ?

**Comment by tyoma** [comment]
Hi @StefanS52u1 ! I'm working diligently day and night to pre-release it this week (as you can see by looking at my latest commits). This and issue #78 are my current priorities.
thanks!

**Comment by tyoma** [comment]
Hey @StefanS52u1, please, check out this version - it has the cumulative threads info support.
https://github.com/tyoma/micro-profiler/releases/tag/v2.0.650.0

**Comment by StefanS52u1** [comment]
Thank you Tyoma. It works but the data does not seems to be very reliable. Al lot of times are below zero....
And i'm observing from time to time "hang up for for more then a few dozen seconds"....  (I'm using 64 Bit).

**Comment by tyoma** [comment]
@StefanS52u1 these things may be related to memory constantly growing - i don't have thread trace reclaim on stop yet. How often do you start/finish threads per second (a rough estimate is ok)?

thanks,
Artem

**Comment by StefanS52u1** [comment]
I think  sometimes, but rare, more then 50 or 100 per second. But usually i guess up to 10 or more per second. But i will measure that today with the performance counters.

**Comment by StefanS52u1** [comment]
After a restart of windows, i did not observe these errors any more. Thanks a lot for the feature.

**Comment by tyoma** [comment]
@StefanS52u1 there were a few issues related to negative times - you may need to fix CPU frequency - usually this is being done in Power Management, by setting min and max CPU performance to 99% - this disables Turbo Boost and alike.

**Comment by tyoma** [comment]
@StefanS52u1 an unrelated thing - just a thought... 10-100 threads starting/stopping per second is a significant performance and memory (since OS has to allocate stack for each) overhead - you may want to consider a queue-based approach in your application.

**Comment by StefanS52u1** [comment]
@tyoma We are already using a thread pool. My information about the tread create count per second ist wrong. If the application is running, the thread count is about 200 threads. Most of new threads reqquests are taken from this pool. Sometime (but very rare - only during startup and may be 1 per hour) there is a burst of about creating 100 new threads.

**Comment by tyoma** [comment]
@StefanS52u1 that's the thing - it should be 99, rather than 100. 100 gives windows freedom in freq boosting.
you can confirm that by looking at Task Manager's Performance tab when selecting 99/99 and 100/100

**Comment by tyoma** [comment]
Implemented as of https://github.com/tyoma/micro-profiler/releases/tag/v2.0.651.0
