### ISSUE TITLE
Viewer will not display any data

### ISSUE THREAD

**Issue by StefanS52u1** [tyoma/micro-profiler#72]
With windows computers, managed by our it, running with kasparsky and some other restriction policies, the viewer within the devstudio will never show profile data. After some research i found out, the there is a racing issue at the startup of server sockets and threads. The server will connect the auxiliary socket and send the initial magic number, but may not wait, until the client is ready to receive data. Therefore the client will not wake up any more (even at shutdown of the devstudio).
An additional sleep as workaround always helped to solve the issue:

		int server::connect_aux(unsigned short port)
			{
				sockaddr_in service = { AF_INET, htons(port), inet_addr(c_localhost), { 0 } };
				int s = static_cast<int>(::socket(AF_INET, SOCK_STREAM, IPPROTO_TCP));
				u_long arg = 1 /* nonblocking */;

				if (-1 == s)
					throw initialization_failed("aux socket creation failed");
				::ioctl(s, O_NONBLOCK, &arg);
				::connect(s, (sockaddr *)&service, sizeof(service));
				::_sleep(50);
				send_scalar(s, init_magic);
				return s;
			}

**Comment by tyoma** [comment]
Thank you, Stefan! I may add the sleep, but it doesn't look like long-term safe solution. I will be thinking on one, meanwhile, I push sleep() for the next release.

**Comment by tyoma** [comment]
Hi @StefanS52u1,
https://github.com/tyoma/micro-profiler/commit/48497f6a87090b90f05f604522438133f9323613 should fix this bug - connect is now done in blocking mode. Should work fine now (at least the tests didn't work and now do on Windows 2003).

**Comment by tyoma** [comment]
@StefanS52u1,

can you please clise this one?

thank you!

**Comment by StefanS52u1** [comment]
Solved. Thanx.
