### ISSUE TITLE
Switch On/Off Microprofiler (with Environment Variable)

### ISSUE THREAD

**Issue by StefanS52u1** [tyoma/micro-profiler#74]
I would like to have a feature to enable and disable the micro-profiler collecting data globally without changing the code. 
The pentry and pexit code will allways be called, but the microprofiler will only collect data, if the feature is enabled.
Then it will be easy to switch on/off the microprofiler, without recompiling or relinking everything. I used an environment variable to control the behavior.

P.S: Some of our  solutions are really big, that even linken takes a few minutes.

**Comment by tyoma** [comment]
for this i had a stub dll with entry functions, perhaps, changing MICROPROFILERDIR to a directory with stub dlls (x86/x64) would solve an issue. i can think of adding this switch to GUI...

**Comment by StefanS52u1** [comment]
@tyoma just a hint, maybe you know that already:
I'm also not enabling/disabling the profiling each project within the visual studio ui. I'm using an predefined environmental variable with a condition entry within the settings to change the behaviour (Because we have more the 350 Projects).
And i don't want to extra configurations for each project only for profiling: 

Vars:
MSBUILD_RELEASE_X86_PENTER_PEXIT_LIBRARY=MICROPROFILER

Settings.props:
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  
  <Target Name="DisablePostBuildEvent" AfterTargets="Link" BeforeTargets="PostBuildEvent">
	<PropertyGroup>
		<PostBuildEventUseInBuild Condition="'$(LinkSkippedExecution)' == 'True'">false</PostBuildEventUseInBuild>
	</PropertyGroup>
  </Target>  
  <ImportGroup Label="PropertySheets">
    <Import Project="SirioReleaseDll_NoPenterPexit.props" />
  </ImportGroup>
  <PropertyGroup>
    <_ProjectFileVersion>10.0.30319.1</_ProjectFileVersion>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <PreprocessorDefinitions>_USRDLL;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions Condition=" '$(MSBUILD_RELEASE_X86_PENTER_PEXIT_LIBRARY)' == 'MICROPROFILER' ">/Oy- /GH /Gh %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <AdditionalDependencies Condition="'$(MSBUILD_RELEASE_X86_PENTER_PEXIT_LIBRARY)' == 'MICROPROFILER'">micro-profiler_win32.lib;%(AdditionalDependencies);</AdditionalDependencies>
      <OutputFile>$(TargetDir)\$(ProjectName).dll</OutputFile>
      <SubSystem>Windows</SubSystem>
    </Link>
  </ItemDefinitionGroup>
</Project>**__**

**Comment by tyoma** [comment]
@StefanS52u1 the snippet you provided got scrambled, but I think I got the idea - default visual studio project attempts to include (if exists) this file: ```$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props``` and you can put (and change) compiler and linker command line options necessary to enable profiling there
