### ISSUE TITLE
Question: Profiling static .lib

### ISSUE THREAD

**Issue by whitwhoa** [tyoma/micro-profiler#75]
It is stated in the readme:
> To profile a static library you may follow the similar steps: enable and then disable profiling on the image (dll/exe) project 
> containing the library and manually add /GH /Gh for the library of interest.

To clarify, if I wish to profile code from within a statically linked .lib file, I need to build the statically linked .lib file with `/GH /Gh` compiler options, and then within the application that is linking to the .lib, right click the project and uncheck `Enable Profiling`? Is that correct?

**Comment by tyoma** [comment]
Hello @whitwhoa,
I think the guide got slightly outdated - if you're in VisualStudio - you can simply right-click the static library and then - "Enable Profile" in the context menu. This should do.
