### ISSUE TITLE
single c file in solution cannot resolve penter / pexit

### ISSUE THREAD

**Issue by Carandiru0** [tyoma/micro-profiler#76]
I have a solution that is 99.9% cpp files, with one c file being used (volk.,c)

On build, with profiling enabled:
```
Finished generating code
1>volk.obj : error LNK2001: unresolved external symbol _penter
1>volk.obj : error LNK2001: unresolved external symbol _pexit
1>C:\MinCity\x64\Release\..\..\MinCity.exe : fatal error LNK1120: 2 unresolved externals
```

I've checked the project, $(MICROPROFILERDIR)/micro-profiler_$(PlatformName).lib is automagically added to additional dependencies.

I tried /Gh- on the one c file to see if I could exclude it.
I also tried overriding the compilation of the c file to be built as c++. Same unresolved symbol.

--------------------------------------------------------------------------------------------------------------------------------------
I also tried copying micro-profiler_x64.lib/dll locally to the project dir, and manually adding it to the additional dependencies,
This seems to work, but manually has to be done to the project.

Any ideas as to what might be causing this issue?

**Comment by tyoma** [comment]
Hello @Carandiru0,
there's a known issue - it may require to restart visual studio twice after installing micro-profiler package - this way the environment variable pointing at the installation location is properly updated.
thank you,
Artem

**Comment by tyoma** [comment]
this is the original issue: https://github.com/tyoma/micro-profiler/issues/69

**Comment by Carandiru0** [comment]
thanks, greater profiler!

**Comment by tyoma** [comment]
thanks, @Carandiru0! when you feel like it - please, leave a review on visual studio marketplace: https://marketplace.visualstudio.com/items?itemName=ArtemGevorkyan.MicroProfilerx64x86
