### ISSUE TITLE
Add VS 2022 support

### ISSUE THREAD

**Issue by talley** [tyoma/micro-profiler#80]
Add VS 2022 support

**Comment by tyoma** [comment]
Hi @talley ! It's implemented a while ago. Did you try it...
* ...here: https://marketplace.visualstudio.com/items?itemName=ArtemGevorkyan.microprofiler-x64-vsix
* ...or here: https://github.com/tyoma/micro-profiler/releases/download/v2.0.650.0/micro-profiler_x64.v2.0.650.0.vsix
?
